version: "3"

networks:
  webnetwork:

services:
  postgres:
    image: postgres:9.6
    networks:
      - webnetwork
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: principles_dev_database
    restart: always
  apigateway:
    networks:
      - webnetwork
    image: tunguyenuni/api-gateway:v1
    volumes:
      - ./apigateway:/usr/src/app
      - ./upload:/user/src/upload
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DB_HOST: postgres
      ES_HOST: elasticsearch
    command: npm run dev
    restart: on-failure
  elasticsearch:
    networks:
      - webnetwork
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
