version: "3"

networks:
  webnetwork:

services:
  postgres:
    image: postgres:10.0
    networks:
      - webnetwork
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: principles_dev_database
    restart: always
  apigateway:
    networks:
      - webnetwork
    image: tunguyenuni/api-gateway:v1
    volumes:
      - ./apigateway:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
    command: npm run dev
    restart: on-failure
