settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 6000
  host: localhost
schema:
- name: main
  path: .
  commands:
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml